### ISSUE TITLE
Add page for Code of Conduct  

### ISSUE THREAD

**Issue by davidjb** [devnq/devnq#31]
Add a page to the website (and links into the site’s footer to said page) that explains DevNQ operates under a code of conduct and where to access the code of conduct, and how someone can report an situation or concern. 

The code of conduct lives at https://github.com/devnq/governance/blob/main/code-of-conduct.md

**Comment by tjdavey** [comment]
This work was completed recently and now lives at https://devnq.org/code-of-conduct.html
