### ISSUE TITLE
Add IPv6 support for GitHub Pages

### ISSUE THREAD

**Issue by davidjb** [devnq/devnq#49]
Could IPv6 records please be added to the DNS for devnq.org?  See https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain= for the specific details of records required.

**Comment by tjdavey** [comment]
AAAA records have been added and are now visible when querying the devnq.org DNS.
