### ISSUE TITLE
Change DNS to allow GitHub Pages to validate domain for TLS

### ISSUE THREAD

**Issue by davidjb** [devnq/devnq#50]
As part of automatic TLS certificates and enforcing HTTPS, GitHub Pages performs checks on the domains associated with this repo. Certs are being issued but checks keep being performed on a loop.  I chatted with GitHub support and the reason is the the record for `www.devnq.org` needs to be adjusted to be a CNAME that points at `devnq.github.io` (it's currently a CNAME for `devnq.org`).

@tjdavey Could you please make the change?  Thanks.

**Comment by tjdavey** [comment]
This has now been resolved.
